print("Removing junk")
fs.delete("startup.lua")
fs.delete("hercules.lua")
print("Installing hercules...")
print("Downloading files")
shell.run("wget https://raw.githubusercontent.com/ShinyRa/ComputerCraftScripts/main/Hesperides/hercules.lua")
print("Running hercules")
shell.run("hercules")
fs.delete("installer.lua")
