print("Installing hercules...")
print("Downloading files")
shell.run("wget https://raw.githubusercontent.com/ShinyRa/ComputerCraftScripts/main/Hesperides/hercules.lua")
print("Running hercules")
shell.run("hercules")